
/**
 * Service to handle email dispatch via Resend API.
 * Assumes process.env.RESEND_API_KEY is configured.
 */
export const sendRescueEmail = async (
  email: string, 
  operationName: string, 
  pptxBase64: string
) => {
  // Note: Resend API requires an API key. 
  // In a real production app, this should be called from a server-side route.
  // We use fetch here to demonstrate the integration logic.
  const apiKey = (process.env as any).RESEND_API_KEY;
  
  if (!apiKey) {
    console.warn("RESEND_API_KEY is not configured. Email sending skipped.");
    return;
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      from: 'Rescue HQ <hq@presorescue.com>',
      to: [email],
      subject: `[CONFIDENTIAL] Tactical Briefing: ${operationName}`,
      html: `
        <div style="font-family: sans-serif; background: #000; color: #fff; padding: 40px; border-radius: 20px;">
          <h1 style="color: #6366f1; text-transform: uppercase;">Mission Confirmed</h1>
          <p>Agent,</p>
          <p>The academic extraction for <strong>${operationName}</strong> is complete.</p>
          <p>Your tactical presentation deck is attached to this briefing. Deploy it with confidence.</p>
          <hr style="border: 1px solid #333; margin: 20px 0;" />
          <p style="font-size: 12px; color: #666;">Generated by PresoRescue AI Command Center.</p>
        </div>
      `,
      attachments: [
        {
          filename: `${operationName.replace(/\s+/g, '_')}_Rescue.pptx`,
          content: pptxBase64,
        },
      ],
    }),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.message || "Failed to send rescue email.");
  }

  return response.json();
};
